package co.uk.wolfnotsheep.platformconfig.listen;

import co.uk.wolfnotsheep.platformconfig.cache.ConfigCacheRegistry;
import co.uk.wolfnotsheep.platformconfig.event.ConfigChangedEvent;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.amqp.rabbit.annotation.RabbitListener;

import java.util.List;

/**
 * Consumes {@code config.changed} messages from the {@code igc.config}
 * exchange and dispatches them to caches + custom listeners.
 *
 * <p>Each replica binds a non-durable, exclusive, auto-delete queue to
 * the exchange — every replica gets every event, no consumer-group
 * semantics. The queue's name is auto-generated by the broker (Spring
 * AMQP handles this when the listener references an anonymous queue).
 *
 * <p>Order of operations per event:
 *
 * <ol>
 *     <li>{@link ConfigCacheRegistry#dispatch(ConfigChangedEvent)} —
 *         caches drop stale entries first.</li>
 *     <li>Custom {@link ConfigChangeListener} beans run — by the time a
 *         listener sees the event, caches have already invalidated, so
 *         downstream side-effects observe the freshly-loaded value.</li>
 * </ol>
 *
 * <p>Failures during listener invocation are logged but never re-raise
 * to the broker. A missed dispatch is a transient correctness gap, not
 * a fatal bug — per CSV #30 and the asyncapi declaration, the next
 * write of the same entity self-heals.
 */
public class ConfigChangeDispatcher {

    private static final Logger log = LoggerFactory.getLogger(ConfigChangeDispatcher.class);

    private final ConfigCacheRegistry registry;
    private final List<ConfigChangeListener> listeners;
    private final ObjectMapper mapper;

    public ConfigChangeDispatcher(
            ConfigCacheRegistry registry,
            List<ConfigChangeListener> listeners,
            ObjectMapper mapper) {
        this.registry = registry;
        this.listeners = listeners;
        this.mapper = mapper;
    }

    @RabbitListener(bindings = @org.springframework.amqp.rabbit.annotation.QueueBinding(
            value = @org.springframework.amqp.rabbit.annotation.Queue(
                    autoDelete = "true",
                    durable = "false",
                    exclusive = "true"),
            exchange = @org.springframework.amqp.rabbit.annotation.Exchange(
                    value = "igc.config",
                    type = "topic",
                    durable = "true"),
            key = "config.changed"))
    public void onMessage(byte[] body) {
        ConfigChangedEvent event;
        try {
            event = mapper.readValue(body, ConfigChangedEvent.class);
        } catch (Exception e) {
            log.warn("config dispatcher: malformed event dropped — {}", e.getMessage());
            return;
        }
        dispatch(event);
    }

    /** Test-friendly entry point — bypasses the AMQP layer. */
    public void dispatch(ConfigChangedEvent event) {
        registry.dispatch(event);
        for (ConfigChangeListener listener : listeners) {
            try {
                listener.onConfigChanged(event);
            } catch (RuntimeException e) {
                log.warn("config dispatcher: listener {} threw on event {}/{}: {}",
                        listener.getClass().getSimpleName(),
                        event.entityType(),
                        event.changeType(),
                        e.getMessage());
            }
        }
    }
}
