spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://root:example@mongo:27017/governance_led_storage_main?authSource=admin}
      auto-index-creation: true
  rabbitmq:
    host: rabbitmq
    port: 5672
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.oauth2.client.servlet.OAuth2ClientAutoConfiguration

minio:
  endpoint: http://minio:9000

logging:
  level:
    co.uk.wolfnotsheep: ${LOG_LEVEL:INFO}
    org.springframework.security: WARN
    org.springframework.web.cors: WARN
