"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import { Save, RefreshCw, Loader2, Settings2, Brain, Gauge, FileText, Cog, DollarSign, Calculator, HardDrive, Eye, EyeOff } from "lucide-react";
import { toast } from "sonner";
import api from "@/lib/axios/axios.client";

type ConfigEntry = {
    id: string;
    key: string;
    category: string;
    value: unknown;
    description: string;
    updatedAt: string;
};

type FieldType = "number" | "slider" | "boolean" | "text" | "textarea" | "select" | "password";

type FieldDef = {
    key: string;
    label: string;
    type: FieldType;
    category: string; // app_config category for saving
    min?: number;
    max?: number;
    step?: number;
    options?: { label: string; value: string }[];
    placeholder?: string;
    helpText?: string;
    group: string;
    groupIcon: React.ElementType;
};

const FIELD_DEFS: FieldDef[] = [
    // Google Drive Integration
    { key: "google.oauth.client_id", label: "Google OAuth Client ID", type: "text", category: "integrations",
        placeholder: "123456789-abc.apps.googleusercontent.com",
        helpText: "From Google Cloud Console > APIs & Services > Credentials",
        group: "Google Drive", groupIcon: HardDrive },
    { key: "google.oauth.client_secret", label: "Google OAuth Client Secret", type: "password", category: "integrations",
        placeholder: "GOCSPX-...",
        helpText: "From Google Cloud Console > APIs & Services > Credentials",
        group: "Google Drive", groupIcon: HardDrive },
    { key: "google.oauth.redirect_uri", label: "OAuth Redirect URI (Drive)", type: "text", category: "integrations",
        placeholder: "http://localhost/api/drives/google/callback",
        helpText: "Add BOTH URIs to Google Cloud Console: this one for Drive connections, and /api/auth/public/google/callback for login.",
        group: "Google Drive", groupIcon: HardDrive },

    // Governance Hub
    { key: "governance.hub.url", label: "Hub URL", type: "text", category: "integrations",
        placeholder: "https://hub.igcentral.com",
        helpText: "URL of the Governance Hub service. For local dev: http://governance-hub:8090",
        group: "Governance Hub", groupIcon: Settings2 },
    { key: "governance.hub.api_key", label: "Hub API Key", type: "password", category: "integrations",
        placeholder: "ghk_...",
        helpText: "API key for accessing the Governance Hub. Generated by the Hub admin.",
        group: "Governance Hub", groupIcon: Settings2 },
];

export default function SettingsPage() {
    const [configs, setConfigs] = useState<Map<string, ConfigEntry>>(new Map());
    const [edited, setEdited] = useState<Map<string, unknown>>(new Map());
    const [saving, setSaving] = useState(false);
    const [refreshing, setRefreshing] = useState(false);

    const loadConfigs = useCallback(async () => {
        try {
            // Load all config categories used by settings fields
            const categories = [...new Set(FIELD_DEFS.map(f => f.category))];
            const results = await Promise.all(
                categories.map(cat => api.get("/admin/config", { params: { category: cat } }))
            );
            const map = new Map<string, ConfigEntry>();
            for (const { data } of results) {
                for (const entry of data) {
                    map.set(entry.key, entry);
                }
            }
            setConfigs(map);
            setEdited(new Map());
        } catch {
            toast.error("Failed to load settings");
        }
    }, []);

    useEffect(() => { loadConfigs(); }, [loadConfigs]);

    const getValue = (key: string): unknown => {
        if (edited.has(key)) return edited.get(key);
        return configs.get(key)?.value;
    };

    const setValue = (key: string, value: unknown) => {
        setEdited((prev) => new Map(prev).set(key, value));
    };

    const hasChanges = edited.size > 0;

    const handleSave = async () => {
        setSaving(true);
        try {
            for (const [key, value] of edited.entries()) {
                const existing = configs.get(key);
                const fieldDef = FIELD_DEFS.find(f => f.key === key);
                await api.put("/admin/config", {
                    key,
                    category: fieldDef?.category ?? "pipeline",
                    value,
                    description: existing?.description ?? fieldDef?.helpText ?? "",
                });
            }
            await api.post("/admin/config/refresh");
            toast.success(`Saved ${edited.size} setting${edited.size > 1 ? "s" : ""}`);
            await loadConfigs();
        } catch {
            toast.error("Failed to save settings");
        } finally {
            setSaving(false);
        }
    };

    const handleRefresh = async () => {
        setRefreshing(true);
        try {
            await api.post("/admin/config/refresh");
            toast.success("Configuration cache refreshed");
        } catch {
            toast.error("Failed to refresh cache");
        } finally {
            setRefreshing(false);
        }
    };

    // Group fields
    const groups = new Map<string, FieldDef[]>();
    for (const field of FIELD_DEFS) {
        if (!groups.has(field.group)) groups.set(field.group, []);
        groups.get(field.group)!.push(field);
    }

    return (
        <>
            {/* Header */}
            <div className="flex items-center justify-between mb-6">
                <div>
                    <h2 className="text-xl font-bold text-gray-900">Settings</h2>
                    <p className="text-sm text-gray-500 mt-1">Configure the platform, integrations, and processing pipeline</p>
                </div>
                <div className="flex items-center gap-3">
                    <button
                        onClick={handleRefresh}
                        disabled={refreshing}
                        className="inline-flex items-center gap-2 px-3 py-2 border border-gray-300 text-sm text-gray-700 rounded-lg hover:bg-gray-50 disabled:opacity-50 transition-colors"
                    >
                        <RefreshCw className={`size-4 ${refreshing ? "animate-spin" : ""}`} />
                        Refresh Cache
                    </button>
                    <button
                        onClick={handleSave}
                        disabled={!hasChanges || saving}
                        className="inline-flex items-center gap-2 px-4 py-2 bg-blue-600 text-white text-sm font-medium rounded-lg hover:bg-blue-700 disabled:opacity-50 transition-colors"
                    >
                        {saving ? <Loader2 className="size-4 animate-spin" /> : <Save className="size-4" />}
                        Save Changes
                        {hasChanges && (
                            <span className="size-5 rounded-full bg-white/20 text-xs flex items-center justify-center">
                                {edited.size}
                            </span>
                        )}
                    </button>
                </div>
            </div>

            {/* Settings groups */}
            <div className="space-y-6">
                {Array.from(groups.entries()).map(([groupName, fields]) => {
                    const GroupIcon = fields[0].groupIcon;
                    return (
                        <div key={groupName} className="bg-white rounded-lg shadow-sm border border-gray-200">
                            <div className="flex items-center gap-2 px-6 py-4 border-b border-gray-200">
                                <GroupIcon className="size-5 text-gray-500" />
                                <h3 className="text-base font-semibold text-gray-900">{groupName}</h3>
                            </div>

                            {/* Setup instructions for Google Drive */}
                            {groupName === "Google Drive" && <GoogleDriveSetupGuide />}

                            <div className="divide-y divide-gray-100">
                                {fields.map((field) => (
                                    <SettingRow
                                        key={field.key}
                                        field={field}
                                        value={getValue(field.key)}
                                        description={configs.get(field.key)?.description ?? field.helpText}
                                        isEdited={edited.has(field.key)}
                                        onChange={(v) => setValue(field.key, v)}
                                    />
                                ))}
                            </div>
                        </div>
                    );
                })}
            </div>

        </>
    );
}

function SettingRow({ field, value, description, isEdited, onChange }: {
    field: FieldDef;
    value: unknown;
    description?: string;
    isEdited: boolean;
    onChange: (v: unknown) => void;
}) {
    return (
        <div className={`px-6 py-4 ${isEdited ? "bg-blue-50/50" : ""}`}>
            <div className="flex items-start justify-between gap-6">
                <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2">
                        <label htmlFor={`setting-${field.key}`} className="text-sm font-medium text-gray-900">{field.label}</label>
                        {isEdited && (
                            <span className="px-1.5 py-0.5 text-xs bg-blue-100 text-blue-700 rounded">Modified</span>
                        )}
                    </div>
                    {description && (
                        <p className="text-xs text-gray-500 mt-0.5">{description}</p>
                    )}
                </div>
                <div className="shrink-0 w-72">
                    <FieldInput id={`setting-${field.key}`} field={field} value={value} onChange={onChange} />
                </div>
            </div>
        </div>
    );
}

function FieldInput({ id, field, value, onChange }: {
    id: string; field: FieldDef; value: unknown; onChange: (v: unknown) => void;
}) {
    const numVal = typeof value === "number" ? value : parseFloat(String(value ?? "0"));
    const strVal = String(value ?? "");

    switch (field.type) {
        case "slider":
            return (
                <div className="flex items-center gap-3">
                    <input
                        id={id}
                        type="range"
                        min={field.min ?? 0}
                        max={field.max ?? 1}
                        step={field.step ?? 0.01}
                        value={numVal}
                        onChange={(e) => onChange(parseFloat(e.target.value))}
                        className="flex-1 h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer accent-blue-600"
                    />
                    <span className="text-sm font-mono text-gray-700 w-12 text-right">
                        {numVal.toFixed(2)}
                    </span>
                </div>
            );

        case "number":
            return (
                <input
                    id={id}
                    type="number"
                    min={field.min}
                    max={field.max}
                    step={field.step}
                    value={numVal}
                    onChange={(e) => onChange(parseInt(e.target.value) || 0)}
                    className="w-full text-sm border border-gray-300 rounded-md px-3 py-1.5 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                />
            );

        case "boolean":
            return (
                <button
                    id={id}
                    role="switch"
                    aria-checked={!!value}
                    aria-label={field.label}
                    onClick={() => onChange(!value)}
                    className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${
                        value ? "bg-blue-600" : "bg-gray-300"
                    }`}
                >
                    <span
                        className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${
                            value ? "translate-x-6" : "translate-x-1"
                        }`}
                    />
                </button>
            );

        case "select":
            return (
                <select
                    id={id}
                    value={strVal}
                    onChange={(e) => onChange(e.target.value)}
                    className="w-full text-sm border border-gray-300 rounded-md px-3 py-1.5 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                >
                    {field.options?.map((opt) => (
                        <option key={opt.value} value={opt.value}>{opt.label}</option>
                    ))}
                </select>
            );

        case "textarea":
            return (
                <textarea
                    id={id}
                    value={strVal}
                    onChange={(e) => onChange(e.target.value)}
                    rows={8}
                    className="w-full text-xs font-mono border border-gray-300 rounded-md px-3 py-2 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 leading-relaxed"
                />
            );

        case "password":
            return <PasswordField id={id} value={strVal} placeholder={field.placeholder} onChange={(v) => onChange(v)} />;

        default:
            return (
                <input
                    id={id}
                    type="text"
                    value={strVal}
                    onChange={(e) => onChange(e.target.value)}
                    placeholder={field.placeholder}
                    className="w-full text-sm border border-gray-300 rounded-md px-3 py-1.5 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                />
            );
    }
}

function PasswordField({ id, value, placeholder, onChange }: { id: string; value: string; placeholder?: string; onChange: (v: string) => void }) {
    const [visible, setVisible] = useState(false);
    return (
        <div className="relative">
            <input
                id={id}
                type={visible ? "text" : "password"}
                value={value}
                onChange={(e) => onChange(e.target.value)}
                placeholder={placeholder}
                className="w-full text-sm border border-gray-300 rounded-md px-3 py-1.5 pr-9 focus:ring-2 focus:ring-blue-500 focus:border-blue-500 font-mono"
            />
            <button onClick={() => setVisible(!visible)} type="button"
                aria-label={visible ? "Hide password" : "Show password"}
                className="absolute right-2 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600">
                {visible ? <EyeOff className="size-4" /> : <Eye className="size-4" />}
            </button>
        </div>
    );
}

type OllamaModel = {
    name: string;
    model: string;
    size: number;
    details: { parameter_size: string; quantization_level: string; family: string };
};

function LlmProviderPanel({ getValue, setValue }: {
    getValue: (key: string) => unknown;
    setValue: (key: string, value: unknown) => void;
}) {
    const provider = String(getValue("llm.provider") ?? "anthropic");
    const isOllama = provider === "ollama";

    const [ollamaModels, setOllamaModels] = useState<OllamaModel[]>([]);
    const [ollamaReachable, setOllamaReachable] = useState<boolean | null>(null);
    const [ollamaLoading, setOllamaLoading] = useState(false);
    const [pullName, setPullName] = useState("");
    const [pulling, setPulling] = useState(false);
    const [pullProgress, setPullProgress] = useState("");

    const loadOllamaModels = useCallback(async () => {
        setOllamaLoading(true);
        try {
            const { data } = await api.get("/admin/ollama/models");
            setOllamaModels(data.models ?? []);
            setOllamaReachable(!data.error);
        } catch { setOllamaReachable(false); }
        finally { setOllamaLoading(false); }
    }, []);

    useEffect(() => { if (isOllama) loadOllamaModels(); }, [isOllama, loadOllamaModels]);

    const handlePull = async () => {
        const name = pullName.trim();
        if (!name) return;
        setPulling(true);
        setPullProgress("Connecting...");
        try {
            const es = new EventSource(`/api/admin/ollama/pull?model=${encodeURIComponent(name)}`, { withCredentials: true });
            es.addEventListener("progress", (e) => {
                try {
                    const d = JSON.parse(e.data);
                    if (d.total && d.completed) {
                        setPullProgress(`${d.status ?? "Downloading"} ${Math.round((d.completed / d.total) * 100)}%`);
                    } else { setPullProgress(d.status ?? "Pulling..."); }
                } catch { setPullProgress("Pulling..."); }
            });
            es.addEventListener("done", () => { es.close(); setPulling(false); setPullProgress(""); setPullName(""); toast.success(`Model ${name} pulled`); loadOllamaModels(); });
            es.addEventListener("error", () => { es.close(); setPulling(false); setPullProgress(""); toast.error("Pull failed"); });
            es.onerror = () => { es.close(); setPulling(false); setPullProgress(""); };
        } catch { setPulling(false); setPullProgress(""); toast.error("Failed"); }
    };

    const handleDelete = async (name: string) => {
        if (!confirm(`Delete model ${name}?`)) return;
        try { await api.delete("/admin/ollama/models", { data: { model: name } }); toast.success(`Deleted ${name}`); loadOllamaModels(); }
        catch { toast.error("Delete failed"); }
    };

    const fmtSize = (b: number) => b > 1e9 ? `${(b / 1e9).toFixed(1)} GB` : b > 1e6 ? `${(b / 1e6).toFixed(0)} MB` : `${b} B`;

    return (
        <div className="border-b border-gray-200">
            {/* Provider selector */}
            <div className="px-6 py-4 flex items-center justify-between">
                <div className="flex-1">
                    <label htmlFor="llm-provider" className="text-sm font-medium text-gray-900 block mb-1">LLM Provider</label>
                    <p className="text-xs text-gray-400">Choose between cloud (Anthropic Claude) or local (Ollama). Save and restart the LLM worker after changing.</p>
                </div>
                <select id="llm-provider" value={provider} onChange={e => setValue("llm.provider", e.target.value)}
                    className="w-64 text-sm border border-gray-300 rounded-md px-3 py-2 ml-6">
                    <option value="anthropic">Anthropic (Claude) — Cloud</option>
                    <option value="ollama">Ollama — Local Model</option>
                </select>
            </div>

            {/* ── Anthropic config ─────────────────────── */}
            {!isOllama && (
                <div className="px-6 pb-4 space-y-3 bg-blue-50/30">
                    <div>
                        <label htmlFor="anthropic-key" className="text-xs font-medium text-gray-700 block mb-1">API Key</label>
                        <PasswordField id="anthropic-key" value={String(getValue("llm.anthropic.api_key") ?? "")}
                            onChange={v => setValue("llm.anthropic.api_key", v)} placeholder="sk-ant-api03-..." />
                        <p className="text-[10px] text-gray-400 mt-0.5">From console.anthropic.com</p>
                    </div>
                    <div>
                        <label htmlFor="anthropic-model" className="text-xs font-medium text-gray-700 block mb-1">Model</label>
                        <select id="anthropic-model" value={String(getValue("llm.anthropic.model") ?? "claude-sonnet-4-20250514")}
                            onChange={e => setValue("llm.anthropic.model", e.target.value)}
                            className="w-full text-sm border border-gray-300 rounded-md px-3 py-2">
                            <option value="claude-sonnet-4-20250514">Claude Sonnet 4 (2025-05-14) — recommended</option>
                            <option value="claude-sonnet-4-latest">Claude Sonnet 4 (Latest)</option>
                            <option value="claude-haiku-4-5-20251001">Claude Haiku 4.5 — fast &amp; cheap</option>
                            <option value="claude-opus-4-20250514">Claude Opus 4 — highest quality</option>
                        </select>
                    </div>
                </div>
            )}

            {/* ── Ollama config ────────────────────────── */}
            {isOllama && (
                <div className="px-6 pb-4 space-y-4 bg-purple-50/30">
                    {/* Connection */}
                    <div>
                        <label htmlFor="ollama-url" className="text-xs font-medium text-gray-700 block mb-1">Ollama URL</label>
                        <div className="flex gap-2">
                            <input id="ollama-url" value={String(getValue("llm.ollama.base_url") ?? "http://localhost:11434")}
                                onChange={e => { setValue("llm.ollama.base_url", e.target.value); setOllamaReachable(null); }}
                                placeholder="http://localhost:11434"
                                className="flex-1 text-sm border border-gray-300 rounded-md px-3 py-2" />
                            <button onClick={async () => {
                                setOllamaLoading(true); setOllamaReachable(null);
                                try {
                                    const { data } = await api.get("/admin/ollama/status");
                                    setOllamaReachable(data.reachable);
                                    if (data.reachable) { toast.success("Ollama is reachable"); loadOllamaModels(); }
                                    else toast.error("Cannot reach Ollama at that URL");
                                } catch { setOllamaReachable(false); toast.error("Connection check failed"); }
                                finally { setOllamaLoading(false); }
                            }} disabled={ollamaLoading}
                                className={`inline-flex items-center gap-1.5 px-4 py-2 text-sm font-medium rounded-md border transition-colors ${
                                    ollamaReachable === true ? "bg-green-50 text-green-700 border-green-300" :
                                    ollamaReachable === false ? "bg-red-50 text-red-700 border-red-300" :
                                    "bg-white text-gray-700 border-gray-300 hover:bg-gray-50"
                                }`}>
                                {ollamaLoading ? <Loader2 className="size-3.5 animate-spin" /> :
                                 ollamaReachable === true ? <Save className="size-3.5" /> :
                                 ollamaReachable === false ? <Brain className="size-3.5" /> :
                                 <Gauge className="size-3.5" />}
                                {ollamaReachable === true ? "Connected" : ollamaReachable === false ? "Failed" : "Test Connection"}
                            </button>
                        </div>
                        <p className="text-[10px] text-gray-400 mt-1">Use http://host.docker.internal:11434 if Ollama runs on the host and the LLM worker is in Docker.</p>
                    </div>

                    {/* Model selector from installed models */}
                    <div>
                        <label htmlFor="ollama-model" className="text-xs font-medium text-gray-700 block mb-1">Model</label>
                        {ollamaModels.length > 0 ? (
                            <select id="ollama-model" value={String(getValue("llm.ollama.model") ?? "")}
                                onChange={e => setValue("llm.ollama.model", e.target.value)}
                                className="w-full text-sm border border-gray-300 rounded-md px-3 py-2">
                                <option value="">Select an installed model...</option>
                                {ollamaModels.map(m => (
                                    <option key={m.name} value={m.name}>
                                        {m.name} ({m.details?.parameter_size}, {fmtSize(m.size)})
                                    </option>
                                ))}
                            </select>
                        ) : (
                            <input id="ollama-model" value={String(getValue("llm.ollama.model") ?? "")}
                                onChange={e => setValue("llm.ollama.model", e.target.value)}
                                placeholder="qwen2.5:32b"
                                className="w-full text-sm border border-gray-300 rounded-md px-3 py-2" />
                        )}
                    </div>

                    {/* Context window */}
                    <div>
                        <label htmlFor="ollama-ctx" className="text-xs font-medium text-gray-700 block mb-1">Context Window (tokens)</label>
                        <input id="ollama-ctx" type="number" min={2048} max={131072} step={1024}
                            value={Number(getValue("llm.ollama.ctx_size") ?? 32768)}
                            onChange={e => setValue("llm.ollama.ctx_size", parseInt(e.target.value) || 32768)}
                            className="w-full text-sm border border-gray-300 rounded-md px-3 py-2" />
                    </div>

                    {/* Installed models */}
                    <div>
                        <div className="flex items-center justify-between mb-2">
                            <span className="text-xs font-medium text-gray-700">Installed Models</span>
                            <button onClick={loadOllamaModels} disabled={ollamaLoading} className="text-xs text-gray-400 hover:text-gray-600">
                                <RefreshCw className={`size-3.5 ${ollamaLoading ? "animate-spin" : ""}`} />
                            </button>
                        </div>

                        {ollamaModels.length > 0 ? (
                            <div className="space-y-1.5">
                                {ollamaModels.map(m => (
                                    <div key={m.name} className="flex items-center justify-between bg-white rounded-lg border border-gray-200 px-3 py-2">
                                        <div className="flex items-center gap-3 min-w-0">
                                            <Brain className="size-4 text-purple-500 shrink-0" />
                                            <div className="min-w-0">
                                                <span className="text-sm font-medium text-gray-900">{m.name}</span>
                                                <div className="flex items-center gap-2 text-[10px] text-gray-400">
                                                    <span>{m.details?.parameter_size}</span>
                                                    <span>{m.details?.quantization_level}</span>
                                                    <span>{fmtSize(m.size)}</span>
                                                </div>
                                            </div>
                                        </div>
                                        <button onClick={() => handleDelete(m.name)}
                                            className="text-xs text-red-400 hover:text-red-600 px-2 py-1"
                                            aria-label={`Delete ${m.name}`}>Delete</button>
                                    </div>
                                ))}
                            </div>
                        ) : ollamaReachable ? (
                            <p className="text-xs text-gray-400">No models installed. Pull one below.</p>
                        ) : null}
                    </div>

                    {/* Pull model */}
                    <div>
                        <label htmlFor="ollama-pull" className="text-xs font-medium text-gray-700 block mb-1">Pull New Model</label>
                        <div className="flex gap-2">
                            <input id="ollama-pull" value={pullName} onChange={e => setPullName(e.target.value)}
                                onKeyDown={e => { if (e.key === "Enter") handlePull(); }}
                                placeholder="e.g. qwen2.5:72b, mistral-small:22b"
                                disabled={pulling}
                                className="flex-1 text-sm border border-gray-300 rounded-md px-3 py-2 disabled:opacity-50" />
                            <button onClick={handlePull} disabled={pulling || !pullName.trim()}
                                className="inline-flex items-center gap-1.5 px-4 py-2 bg-purple-600 text-white text-sm font-medium rounded-md hover:bg-purple-700 disabled:opacity-50">
                                {pulling ? <Loader2 className="size-3.5 animate-spin" /> : null}
                                {pulling ? "Pulling..." : "Pull"}
                            </button>
                        </div>
                        {pullProgress && (
                            <div className="mt-2 text-xs text-purple-600 font-mono bg-purple-50 rounded px-3 py-1.5">{pullProgress}</div>
                        )}
                    </div>
                </div>
            )}
        </div>
    );
}

function GoogleDriveSetupGuide() {
    const [open, setOpen] = useState(false);
    return (
        <div className="px-6 py-3 bg-blue-50 border-b border-blue-100">
            <button onClick={() => setOpen(!open)}
                className="flex items-center gap-2 text-sm text-blue-700 hover:text-blue-800 font-medium w-full text-left">
                <Settings2 className="size-4" />
                {open ? "Hide setup instructions" : "How to set up Google Drive integration"}
            </button>
            {open && (
                <div className="mt-3 text-xs text-blue-800 space-y-3">
                    <ol className="space-y-2 list-decimal ml-4">
                        <li>
                            Go to <a href="https://console.cloud.google.com" target="_blank" rel="noopener noreferrer"
                                className="underline font-medium">console.cloud.google.com</a> and create a project (or select an existing one).
                        </li>
                        <li>
                            <strong>Enable the Google Drive API:</strong> Go to <em>APIs &amp; Services &rarr; Library</em>, search for
                            &quot;Google Drive API&quot;, and click <strong>Enable</strong>.
                        </li>
                        <li>
                            <strong>Configure the OAuth consent screen:</strong> Go to <em>APIs &amp; Services &rarr; OAuth consent screen</em>.
                            <ul className="list-disc ml-4 mt-1 space-y-0.5">
                                <li>Choose <strong>External</strong> (or Internal if you have Google Workspace)</li>
                                <li>Fill in the app name (e.g. &quot;IG Central&quot;), support email, developer email</li>
                                <li>Add scopes: <code className="bg-blue-100 px-1 rounded">drive.readonly</code>, <code className="bg-blue-100 px-1 rounded">userinfo.email</code>, <code className="bg-blue-100 px-1 rounded">userinfo.profile</code></li>
                                <li>Add your email as a <strong>test user</strong> (required while app is in &quot;Testing&quot; mode)</li>
                            </ul>
                        </li>
                        <li>
                            <strong>Create OAuth credentials:</strong> Go to <em>APIs &amp; Services &rarr; Credentials &rarr; Create Credentials &rarr; OAuth client ID</em>.
                            <ul className="list-disc ml-4 mt-1 space-y-0.5">
                                <li>Application type: <strong>Web application</strong></li>
                                <li>Name: &quot;IG Central&quot;</li>
                                <li>Authorised redirect URIs — add <strong>both</strong>:<br/>
                                <code className="bg-blue-100 px-1 rounded">http://localhost/api/drives/google/callback</code> (Drive connection)<br/>
                                <code className="bg-blue-100 px-1 rounded">http://localhost/api/auth/public/google/callback</code> (Login with Google)</li>
                            </ul>
                        </li>
                        <li>
                            Copy the <strong>Client ID</strong> and <strong>Client Secret</strong> from Google and paste them into the fields below.
                        </li>
                        <li>
                            Click <strong>Save Changes</strong>. Users can then connect their Google Drive from the <strong>Drives</strong> page.
                        </li>
                    </ol>
                    <div className="bg-blue-100 rounded p-2.5 border border-blue-200">
                        <p className="font-medium">Important notes:</p>
                        <ul className="list-disc ml-4 mt-1 space-y-0.5">
                            <li>While your Google Cloud app is in &quot;Testing&quot; mode, only emails added as test users can connect.</li>
                            <li>To allow anyone in your Google Workspace domain, switch to &quot;Internal&quot; on the consent screen.</li>
                            <li>For production, submit for Google verification to remove the &quot;unverified app&quot; warning.</li>
                            <li>Documents stay in Google Drive — only metadata and extracted text are stored in IG Central.</li>
                        </ul>
                    </div>
                </div>
            )}
        </div>
    );
}

/* ── Cost Estimator ────────────────────────────────── */

const MODEL_PRICING: Record<string, { input: number; output: number; label: string }> = {
    "claude-sonnet-4-20250514":   { input: 3.00,  output: 15.00, label: "Sonnet 4" },
    "claude-sonnet-4-latest":     { input: 3.00,  output: 15.00, label: "Sonnet 4" },
    "claude-3-5-haiku-20241022":  { input: 0.80,  output: 4.00,  label: "Haiku 3.5" },
    "claude-opus-4-20250514":     { input: 15.00, output: 75.00, label: "Opus 4" },
};

// ~4 chars per token is a reasonable estimate for English text
const CHARS_PER_TOKEN = 4;
// System prompt + tool definitions are roughly this many tokens
const SYSTEM_OVERHEAD_TOKENS = 2000;
// MCP tool calls (taxonomy, policies, retention etc) add roughly this many tokens round-trip
const TOOL_CALL_OVERHEAD_TOKENS = 3000;

function CostEstimator({ model, maxTokens, maxTextLength }: {
    model: string; maxTokens: number; maxTextLength: number;
}) {
    const [docsPerMonth, setDocsPerMonth] = useState(100);
    const [avgDocChars, setAvgDocChars] = useState(20000);

    const pricing = MODEL_PRICING[model] ?? MODEL_PRICING["claude-sonnet-4-20250514"];

    const estimate = useMemo(() => {
        const inputChars = Math.min(avgDocChars, maxTextLength);
        const inputTokens = Math.ceil(inputChars / CHARS_PER_TOKEN) + SYSTEM_OVERHEAD_TOKENS + TOOL_CALL_OVERHEAD_TOKENS;
        const outputTokens = Math.min(maxTokens, 2000); // typical classification response ~1500-2000 tokens

        const costPerDocInput = (inputTokens / 1_000_000) * pricing.input;
        const costPerDocOutput = (outputTokens / 1_000_000) * pricing.output;
        const costPerDoc = costPerDocInput + costPerDocOutput;

        const monthlyCost = costPerDoc * docsPerMonth;
        const yearlyCost = monthlyCost * 12;

        return {
            inputTokens,
            outputTokens,
            costPerDoc,
            monthlyCost,
            yearlyCost,
            costPerDocInput,
            costPerDocOutput,
        };
    }, [avgDocChars, maxTextLength, maxTokens, pricing, docsPerMonth]);

    return (
        <div className="bg-white rounded-lg shadow-sm border border-gray-200 mt-6">
            <div className="flex items-center gap-2 px-6 py-4 border-b border-gray-200">
                <Calculator className="size-5 text-gray-500" />
                <h3 className="text-base font-semibold text-gray-900">Cost Estimator</h3>
                <span className="text-xs text-gray-400 ml-auto">Based on current Anthropic API pricing</span>
            </div>

            <div className="p-6">
                {/* Inputs */}
                <div className="grid grid-cols-2 gap-6 mb-6">
                    <div>
                        <label htmlFor="cost-docs-per-month" className="text-sm font-medium text-gray-700 block mb-1">Documents per month</label>
                        <input
                            id="cost-docs-per-month"
                            type="number"
                            min={1}
                            max={100000}
                            value={docsPerMonth}
                            onChange={(e) => setDocsPerMonth(parseInt(e.target.value) || 1)}
                            className="w-full text-sm border border-gray-300 rounded-md px-3 py-1.5 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                        />
                    </div>
                    <div>
                        <label htmlFor="cost-avg-doc-chars" className="text-sm font-medium text-gray-700 block mb-1">Avg document size (chars)</label>
                        <input
                            id="cost-avg-doc-chars"
                            type="number"
                            min={100}
                            max={500000}
                            step={1000}
                            value={avgDocChars}
                            onChange={(e) => setAvgDocChars(parseInt(e.target.value) || 1000)}
                            className="w-full text-sm border border-gray-300 rounded-md px-3 py-1.5 focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                        />
                    </div>
                </div>

                {/* Cost breakdown */}
                <div className="grid grid-cols-3 gap-4 mb-6">
                    <CostCard
                        label="Per Document"
                        amount={estimate.costPerDoc}
                        detail={`~${(estimate.inputTokens + estimate.outputTokens).toLocaleString()} tokens`}
                        accent="blue"
                    />
                    <CostCard
                        label="Monthly"
                        amount={estimate.monthlyCost}
                        detail={`${docsPerMonth.toLocaleString()} docs`}
                        accent="green"
                    />
                    <CostCard
                        label="Yearly"
                        amount={estimate.yearlyCost}
                        detail={`${(docsPerMonth * 12).toLocaleString()} docs`}
                        accent="purple"
                    />
                </div>

                {/* Token breakdown */}
                <div className="bg-gray-50 rounded-lg p-4 text-xs space-y-2">
                    <div className="flex items-center justify-between font-medium text-gray-700">
                        <span>Token breakdown per document</span>
                        <span className="text-gray-500">{pricing.label} pricing</span>
                    </div>
                    <div className="flex items-center justify-between text-gray-600">
                        <span>Input tokens (document + system + tools)</span>
                        <span>{estimate.inputTokens.toLocaleString()} @ ${pricing.input}/1M = ${estimate.costPerDocInput.toFixed(4)}</span>
                    </div>
                    <div className="flex items-center justify-between text-gray-600">
                        <span>Output tokens (classification response)</span>
                        <span>{estimate.outputTokens.toLocaleString()} @ ${pricing.output}/1M = ${estimate.costPerDocOutput.toFixed(4)}</span>
                    </div>
                    <div className="border-t border-gray-200 pt-2 flex items-center justify-between font-medium text-gray-700">
                        <span>Total per document</span>
                        <span>${estimate.costPerDoc.toFixed(4)}</span>
                    </div>
                    <p className="text-gray-400 pt-1">
                        Estimates assume ~4 chars/token, ~2K system prompt tokens, ~3K tool-call overhead, and ~2K output tokens per classification.
                        Actual costs may vary based on document complexity and tool usage patterns.
                    </p>
                </div>
            </div>
        </div>
    );
}

function CostCard({ label, amount, detail, accent }: {
    label: string; amount: number; detail: string; accent: "blue" | "green" | "purple";
}) {
    const colors = {
        blue: "bg-blue-50 border-blue-200",
        green: "bg-green-50 border-green-200",
        purple: "bg-purple-50 border-purple-200",
    };
    const textColors = {
        blue: "text-blue-700",
        green: "text-green-700",
        purple: "text-purple-700",
    };
    return (
        <div className={`rounded-lg border p-4 ${colors[accent]}`}>
            <div className="text-xs font-medium text-gray-500 mb-1">{label}</div>
            <div className={`text-xl font-bold ${textColors[accent]}`}>
                ${amount < 0.01 ? amount.toFixed(4) : amount < 1 ? amount.toFixed(3) : amount.toFixed(2)}
            </div>
            <div className="text-xs text-gray-500 mt-0.5">{detail}</div>
        </div>
    );
}
