package co.uk.wolfnotsheep.document.models;

public enum DocumentStatus {
    UPLOADING,
    UPLOADED,
    PROCESSING,
    PROCESSING_FAILED,
    PROCESSED,
    CLASSIFYING,
    CLASSIFICATION_FAILED,
    CLASSIFIED,
    ENFORCEMENT_FAILED,
    REVIEW_REQUIRED,
    GOVERNANCE_APPLIED,
    INBOX,
    FILED,
    ARCHIVED,
    DISPOSED
}
